"""End-to-end convert_plugin: emit a loadable native plugin + report, with the regenerable gate."""

import json

import pytest

from harness.catalog import Catalog
from harness.cc_import import CcImportError, convert_plugin
from harness.plugins import load_plugins

CATALOG = Catalog(entries={"sonnet": {"route": "anthropic/claude-sonnet"}})

_HAND_TOML = (
    "[plugin]\nname="
    + repr("demo")
    + "\nversion="
    + repr("1")
    + "\ndescription="
    + repr("d")
    + "\n"
)


def _cc(root, files, plugin_json=None):
    meta = root / ".claude-plugin"
    meta.mkdir(parents=True)
    (meta / "plugin.json").write_text(
        json.dumps(plugin_json or {"name": "demo", "version": "1.0.0", "description": "d"})
    )
    for rel, content in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
    return root


def test_convert_emits_loadable_plugin_and_report(tmp_path):
    src = _cc(
        tmp_path / "cc",
        {
            "skills/remembering/SKILL.md": "---\nname: remembering\ndescription: d\n---\nUse `Read`.\n",
            "commands/greet.md": "---\ndescription: g\n---\nHi $ARGUMENTS\n",
            "agents/scout.md": "---\nname: scout\ndescription: d\ntools: Read, Bash\n---\nGo.\n",
        },
    )
    out = tmp_path / "out" / "demo"
    result = convert_plugin(src, out=out, catalog=CATALOG)
    assert (out / "plugin.toml").is_file()
    assert (out / "skills" / "remembering.md").is_file()
    assert (out / "IMPORT-REPORT.md").is_file()
    # the gate: it actually loads
    loaded = load_plugins([out.parent])
    assert [p.name for p in loaded.plugins] == ["demo"]
    assert any(s.name == "remembering" for s in loaded.skills)
    assert result.report_path == out / "IMPORT-REPORT.md"


def test_convert_is_idempotent_byte_for_byte(tmp_path):
    src = _cc(
        tmp_path / "cc", {"skills/a/SKILL.md": "---\nname: a\ndescription: d\n---\nUse `Edit`.\n"}
    )
    out1 = tmp_path / "o1" / "demo"
    out2 = tmp_path / "o2" / "demo"
    convert_plugin(src, out=out1, catalog=CATALOG)
    convert_plugin(src, out=out2, catalog=CATALOG)
    for rel in ("plugin.toml", "skills/a.md", "IMPORT-REPORT.md"):
        assert (out1 / rel).read_text() == (out2 / rel).read_text()


def test_reimport_over_generated_target_overwrites(tmp_path):
    src = _cc(tmp_path / "cc", {"skills/a/SKILL.md": "---\nname: a\ndescription: d\n---\nx\n"})
    out = tmp_path / "out" / "demo"
    convert_plugin(src, out=out, catalog=CATALOG)
    # second import over the generated marker is allowed
    result = convert_plugin(src, out=out, catalog=CATALOG)
    assert (out / "plugin.toml").is_file()
    assert result.overwritten is True


def test_reimport_over_hand_made_target_refuses(tmp_path):
    src = _cc(tmp_path / "cc", {"skills/a/SKILL.md": "---\nname: a\ndescription: d\n---\nx\n"})
    out = tmp_path / "out" / "demo"
    out.mkdir(parents=True)
    (out / "plugin.toml").write_text(_HAND_TOML)
    with pytest.raises(CcImportError) as exc:
        convert_plugin(src, out=out, catalog=CATALOG)
    assert "not generated by harness import" in str(exc.value)
    assert "--force" in str(exc.value)


def test_force_overrides_refusal(tmp_path):
    src = _cc(tmp_path / "cc", {"skills/a/SKILL.md": "---\nname: a\ndescription: d\n---\nx\n"})
    out = tmp_path / "out" / "demo"
    out.mkdir(parents=True)
    (out / "plugin.toml").write_text(_HAND_TOML)
    convert_plugin(src, out=out, catalog=CATALOG, force=True)
    from harness.cc_import import has_generated_marker

    assert has_generated_marker(out / "plugin.toml") is True  # now a generated artifact


def test_broken_emission_fails_loudly_emits_nothing(tmp_path, monkeypatch):
    # force an emitted skill that cannot load: a duplicate skill name across two CC skills
    src = _cc(
        tmp_path / "cc",
        {
            "skills/dup/SKILL.md": "---\nname: same\ndescription: d\n---\nx\n",
            "skills/dup2/SKILL.md": "---\nname: same\ndescription: d\n---\ny\n",
        },
    )
    out = tmp_path / "out" / "demo"
    with pytest.raises(CcImportError):
        convert_plugin(src, out=out, catalog=CATALOG)
    assert not out.exists()  # nothing published on failure (validate-by-loading, L13)


def test_mcp_servers_emitted_and_load(tmp_path):
    src = _cc(
        tmp_path / "cc",
        {
            ".mcp.json": json.dumps(
                {
                    "mcpServers": {
                        "s": {"command": "${CLAUDE_PLUGIN_ROOT}/run", "env": {"K": "${MY_VAR}"}}
                    }
                }
            ),
        },
    )
    out = tmp_path / "out" / "demo"
    convert_plugin(src, out=out, catalog=CATALOG)
    loaded = load_plugins([out.parent])
    (server,) = loaded.mcp_servers
    assert server.name == "s"
    assert server.env == {"K": "MY_VAR"}
